# Generated by Django 5.1.6 on 2025-03-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.IntegerField()),
                ('DeliveryLocation', models.CharField(max_length=250)),
                ('CustomerId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockId', models.IntegerField()),
                ('OrderId', models.IntegerField()),
                ('StockName', models.CharField(max_length=64)),
                ('RequestedQTY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockId', models.IntegerField()),
                ('StockName', models.CharField(max_length=64)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('QTY', models.IntegerField()),
            ],
        ),
    ]
