# Generated by Django 5.1.6 on 2025-03-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerId', models.IntegerField()),
                ('CFirstName', models.CharField(max_length=250)),
                ('CSurname', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeId', models.IntegerField()),
                ('FirstName', models.CharField(max_length=250)),
                ('Surname', models.CharField(max_length=250)),
                ('Job', models.CharField(max_length=250)),
            ],
        ),
    ]
