# Generated by Django 5.1.6 on 2025-03-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0002_customer_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='CEmail',
            field=models.EmailField(default='example@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='CPassword',
            field=models.CharField(default='password1234', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.EmailField(default='example@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='Password',
            field=models.CharField(default='password1234', max_length=250),
        ),
    ]
