# Generated by Django 5.1.6 on 2025-03-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0003_customer_cemail_customer_cpassword_employee_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='CustomerId',
        ),
    ]
