# Generated by Django 5.1.6 on 2025-03-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0004_remove_customer_customerid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='delivery',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
