# Generated by Django 5.1.6 on 2025-03-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0005_delete_delivery_delete_employee_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='CSurname',
            new_name='CUsername',
        ),
    ]
